// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mantis.Automacao.tst.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Criar nova conta")]
    public partial class CriarNovaContaFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Criar novo usuario.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Criar nova conta", "\tComo: Administrador\r\n\tQuero: Criar nova conta\r\n\tPara: Que outrar pessoas possam " +
                    "usar o Mantis", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
 testRunner.Given("eu esteja logado como administrador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Criar nova conta valida")]
        [NUnit.Framework.CategoryAttribute("CriarConta")]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "usuarioteste@teste.com", "vizualizador", null)]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "usuarioteste@teste.com", "relator", null)]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "usuarioteste@teste.com", "atualizador", null)]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "usuarioteste@teste.com", "desenvolvedor", null)]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "usuarioteste@teste.com", "gerente", null)]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "usuarioteste@teste.com", "administrador", null)]
        public virtual void CriarNovaContaValida(string uSERNAME, string rEAL_NAME, string e_MAIL, string aCCESS_LEVEL, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CriarConta"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar nova conta valida", null, @__tags);
#line 11
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
this.FeatureBackground();
#line 12
 testRunner.And("entre na tela de criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When(string.Format("eu preencher as informacoes do novo usuario: \'{0}\', \'{1}\', \'{2}\' e <\'ACCESS_LEVEL" +
                        "\'>", uSERNAME, rEAL_NAME, e_MAIL), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.And("clicar para criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.Then("eu tenho a confirmacao de que o usuario foi criado corretamente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.And("o novo usuario dever ter sido criado corretamente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Criar nova conta com nome do usuario repetido")]
        public virtual void CriarNovaContaComNomeDoUsuarioRepetido()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar nova conta com nome do usuario repetido", null, ((string[])(null)));
#line 27
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
this.FeatureBackground();
#line 28
 testRunner.And("entre na tela de criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("eu preencher as informacoes do novo usuario: \'usuarioTeste\', \'nomeDiferente\', \'te" +
                    "ste@teste.com\' e \'vizualizador\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.And("clicar para criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.Then("eu vejo uma mensagem de que nao e possivel criar usuario com nome repetido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Criar nova conta com nome do usuario invalido")]
        [NUnit.Framework.TestCaseAttribute("teste*", "nomeRealTeste", "usuarioteste@teste.com", "vizualizador", null)]
        [NUnit.Framework.TestCaseAttribute("teste.", "nomeRealTeste", "usuarioteste@teste.com", "relator", null)]
        [NUnit.Framework.TestCaseAttribute("teste?", "nomeRealTeste", "usuarioteste@teste.com", "atualizador", null)]
        [NUnit.Framework.TestCaseAttribute("teste%", "nomeRealTeste", "usuarioteste@teste.com", "desenvolvedor", null)]
        [NUnit.Framework.TestCaseAttribute("teste#", "nomeRealTeste", "usuarioteste@teste.com", "gerente", null)]
        [NUnit.Framework.TestCaseAttribute("", "nomeRealTeste", "usuarioteste@teste.com", "administrador", null)]
        public virtual void CriarNovaContaComNomeDoUsuarioInvalido(string uSERNAME, string rEAL_NAME, string e_MAIL, string aCCESS_LEVEL, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar nova conta com nome do usuario invalido", null, exampleTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
this.FeatureBackground();
#line 35
 testRunner.And("entre na tela de criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.When(string.Format("eu preencher as informacoes do novo usuario: \'{0}\', \'{1}\', \'{2}\' e <\'ACCESS_LEVEL" +
                        "\'>", uSERNAME, rEAL_NAME, e_MAIL), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.And("clicar para criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.Then("eu vejo uma mensagem de erro dizendo que o nome do usuario esta invalido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
 testRunner.And("o novo usuario dever ter sido criado corretamente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Criar nova conta com e-mail invalido")]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "teste.com", "vizualizador", null)]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "@teste.com", "relator", null)]
        [NUnit.Framework.TestCaseAttribute("usuarioTeste", "nomeRealTeste", "usuarioteste", "atualizador", null)]
        public virtual void CriarNovaContaComE_MailInvalido(string uSERNAME, string rEAL_NAME, string e_MAIL, string aCCESS_LEVEL, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar nova conta com e-mail invalido", null, exampleTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
this.FeatureBackground();
#line 52
 testRunner.And("entre na tela de criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.When(string.Format("eu preencher as informacoes do novo usuario: \'{0}\', \'{1}\', \'{2}\' e <\'ACCESS_LEVEL" +
                        "\'>", uSERNAME, rEAL_NAME, e_MAIL), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.And("clicar para criar nova conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.Then("eu vejo uma mensagem de erro dizendo que o e-mail esta invalido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
 testRunner.And("o novo usuario nao dever ter sido criado corretamente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
