//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantis.Automacao.tst.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssertionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssertionsMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mantis.Automacao.tst.Resources.AssertionsMessages", typeof(AssertionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The browser is not in the login page!.
        /// </summary>
        internal static string AmInLoginPageFail {
            get {
                return ResourceManager.GetString("AmInLoginPageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The browser is in the login page!.
        /// </summary>
        internal static string AmInLoginPageSuccess {
            get {
                return ResourceManager.GetString("AmInLoginPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The browser is not in the manage project page!.
        /// </summary>
        internal static string AmInManageProjectPageFail {
            get {
                return ResourceManager.GetString("AmInManageProjectPageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The browser is in the manage project page!.
        /// </summary>
        internal static string AmInManageProjectPageSuccess {
            get {
                return ResourceManager.GetString("AmInManageProjectPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The browser is not in the password page!.
        /// </summary>
        internal static string AmInPasswordPageFail {
            get {
                return ResourceManager.GetString("AmInPasswordPageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The browser is in the password page!.
        /// </summary>
        internal static string AmInPasswordPageSuccess {
            get {
                return ResourceManager.GetString("AmInPasswordPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The category was not created successfully!.
        /// </summary>
        internal static string CategoryCreatedFail {
            get {
                return ResourceManager.GetString("CategoryCreatedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The category was created successfully!.
        /// </summary>
        internal static string CategoryCreatedSucces {
            get {
                return ResourceManager.GetString("CategoryCreatedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The correct error was not displayed!.
        /// </summary>
        internal static string ErrorDisplayedFail {
            get {
                return ResourceManager.GetString("ErrorDisplayedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The correct error was displayed!.
        /// </summary>
        internal static string ErrorDisplayedSuccess {
            get {
                return ResourceManager.GetString("ErrorDisplayedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The correct error message was not displayed!.
        /// </summary>
        internal static string ErrorMessageFail {
            get {
                return ResourceManager.GetString("ErrorMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The correct error message was dislpayed!.
        /// </summary>
        internal static string ErrorMessageSuccess {
            get {
                return ResourceManager.GetString("ErrorMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The operation failed!.
        /// </summary>
        internal static string OperationFail {
            get {
                return ResourceManager.GetString("OperationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The operation was successfull!.
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The project not was created successfully!.
        /// </summary>
        internal static string ProjectCreatedFail {
            get {
                return ResourceManager.GetString("ProjectCreatedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The project was created successfully!.
        /// </summary>
        internal static string ProjectCreatedSuccess {
            get {
                return ResourceManager.GetString("ProjectCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user was note created successfully!.
        /// </summary>
        internal static string UserCreatedFail {
            get {
                return ResourceManager.GetString("UserCreatedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user was created successfully!.
        /// </summary>
        internal static string UserCreatedSucces {
            get {
                return ResourceManager.GetString("UserCreatedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user loged in successfully!.
        /// </summary>
        internal static string UserLogedInSuccess {
            get {
                return ResourceManager.GetString("UserLogedInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user failed to log in!.
        /// </summary>
        internal static string UserLoggedInFail {
            get {
                return ResourceManager.GetString("UserLoggedInFail", resourceCulture);
            }
        }
    }
}
